// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheStoreProject.Models;

namespace TheStoreProject.Migrations
{
    [DbContext(typeof(ItemDBContext))]
    [Migration("20210404055041_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheStoreProject.Models.Category", b =>
                {
                    b.Property<int>("CATEGORY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CATEGORY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CATEGORY_ID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("TheStoreProject.Models.ItemMaster", b =>
                {
                    b.Property<int>("CATEGORY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BUYER_ID")
                        .HasColumnType("int");

                    b.Property<string>("BUYER_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DISCOUNT_PERCENTAGE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("INNER_PACK_QTY")
                        .HasColumnType("int");

                    b.Property<string>("ITEM_CATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITEM_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ITEM_ID")
                        .HasColumnType("int");

                    b.Property<string>("ITEM_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ITEM_UPC")
                        .HasColumnType("int");

                    b.Property<decimal>("RETAIL_PRICE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SUPPLIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SUPPLIER_ID")
                        .HasColumnType("int");

                    b.HasKey("CATEGORY_ID");

                    b.ToTable("itemMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
